### ISSUE TITLE
[FEATURE] README 작성

### ISSUE THREAD

**Issue by sena-22** [sena-22/pre-onboarding-10th-2-9#9]
### 🤸 Describe the required feature
readme 작성
### 🏊 Todo

- [x] 프로젝트 소개
- [x] 로컬 캐싱 구현 방법 기술
- [x] API 호출 횟수 전략 기술
- [x] 키보드로 추천 검색어 이동 방법 기술
